// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

namespace Kopernicus
{
    namespace MaterialWrapper
    {
        public class AerialTransCutout : Material
        {
            // Internal property ID tracking object
            protected class Properties
            {
                // Return the shader for this wrapper
                private const string shaderName = "Terrain/PQS/Aerial Cutout";
                public static Shader shader
                {
                    get { return Shader.Find (shaderName); }
                }

                // Main Color, default = (1,1,1,1)
                public const string colorKey = "_Color";
                public int colorID { get; private set; }

                // Base (RGB) Trans (A), default = "white" { }
                public const string mainTexKey = "_MainTex";
                public int mainTexID { get; private set; }

                // Alpha cutoff, default = 0.5
                public const string texCutoffKey = "_texCutoff";
                public int texCutoffID { get; private set; }

                // AP Fog Color, default = (0,0,1,1)
                public const string fogColorKey = "_fogColor";
                public int fogColorID { get; private set; }

                // AP Height Fall Off, default = 1
                public const string heightFallOffKey = "_heightFallOff";
                public int heightFallOffID { get; private set; }

                // AP Global Density, default = 1
                public const string globalDensityKey = "_globalDensity";
                public int globalDensityID { get; private set; }

                // AP Atmosphere Depth, default = 1
                public const string atmosphereDepthKey = "_atmosphereDepth";
                public int atmosphereDepthID { get; private set; }

                // Singleton instance
                private static Properties singleton = null;
                public static Properties Instance
                {
                    get
                    {
                        // Construct the singleton if it does not exist
                        if(singleton == null)
                            singleton = new Properties();
            
                        return singleton;
                    }
                }

                private Properties()
                {
                    colorID = Shader.PropertyToID(colorKey);
                    mainTexID = Shader.PropertyToID(mainTexKey);
                    texCutoffID = Shader.PropertyToID(texCutoffKey);
                    fogColorID = Shader.PropertyToID(fogColorKey);
                    heightFallOffID = Shader.PropertyToID(heightFallOffKey);
                    globalDensityID = Shader.PropertyToID(globalDensityKey);
                    atmosphereDepthID = Shader.PropertyToID(atmosphereDepthKey);
                }
            }
            
            // Is some random material this material 
            public static bool UsesSameShader(Material m)
            {
                return m.shader.name == Properties.shader.name;
            }

            // Main Color, default = (1,1,1,1)
            public Color color
            {
                get { return GetColor (Properties.Instance.colorID); }
                set { SetColor (Properties.Instance.colorID, value); }
            }

            // Base (RGB) Trans (A), default = "white" { }
            public Texture2D mainTex
            {
                get { return GetTexture (Properties.Instance.mainTexID) as Texture2D; }
                set { SetTexture (Properties.Instance.mainTexID, value); }
            }

            public Vector2 mainTexScale
            {
                get { return GetTextureScale (Properties.mainTexKey); }
                set { SetTextureScale (Properties.mainTexKey, value); }
            }

            public Vector2 mainTexOffset
            {
                get { return GetTextureOffset (Properties.mainTexKey); }
                set { SetTextureOffset (Properties.mainTexKey, value); }
            }

            // Alpha cutoff, default = 0.5
            public float texCutoff
            {
                get { return GetFloat (Properties.Instance.texCutoffID); }
                set { SetFloat (Properties.Instance.texCutoffID, Mathf.Clamp(value,0f,1f)); }
            }

            // AP Fog Color, default = (0,0,1,1)
            public Color fogColor
            {
                get { return GetColor (Properties.Instance.fogColorID); }
                set { SetColor (Properties.Instance.fogColorID, value); }
            }

            // AP Height Fall Off, default = 1
            public float heightFallOff
            {
                get { return GetFloat (Properties.Instance.heightFallOffID); }
                set { SetFloat (Properties.Instance.heightFallOffID, value); }
            }

            // AP Global Density, default = 1
            public float globalDensity
            {
                get { return GetFloat (Properties.Instance.globalDensityID); }
                set { SetFloat (Properties.Instance.globalDensityID, value); }
            }

            // AP Atmosphere Depth, default = 1
            public float atmosphereDepth
            {
                get { return GetFloat (Properties.Instance.atmosphereDepthID); }
                set { SetFloat (Properties.Instance.atmosphereDepthID, value); }
            }

            public AerialTransCutout() : base(Properties.shader)
            {
            }

            public AerialTransCutout(string contents) : base(contents)
            {
                base.shader = Properties.shader;
            }

            public AerialTransCutout(Material material) : base(material)
            {
                // Throw exception if this material was not the proper material
                if (material.shader.name != Properties.shader.name)
                    throw new InvalidOperationException("Type Mismatch: Terrain/PQS/Aerial Cutout shader required");
            }

        }
    }
}
