// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

namespace Kopernicus
{
    namespace MaterialWrapper
    {
        public class DiffuseWrap : Material
        {
            // Internal property ID tracking object
            protected class Properties
            {
                // Return the shader for this wrapper
                private const string shaderName = "Diffuse Wrapped";
                public static Shader shader
                {
                    get { return Shader.Find (shaderName); }
                }

                // Texture, default = "white" { }
                public const string mainTexKey = "_MainTex";
                public int mainTexID { get; private set; }

                // Main Color, default = (1,1,1,1)
                public const string colorKey = "_Color";
                public int colorID { get; private set; }

                // Diffuse, default = 2
                public const string diffKey = "_Diff";
                public int diffID { get; private set; }

                // Singleton instance
                private static Properties singleton = null;
                public static Properties Instance
                {
                    get
                    {
                        // Construct the singleton if it does not exist
                        if(singleton == null)
                            singleton = new Properties();
            
                        return singleton;
                    }
                }

                private Properties()
                {
                    mainTexID = Shader.PropertyToID(mainTexKey);
                    colorID = Shader.PropertyToID(colorKey);
                    diffID = Shader.PropertyToID(diffKey);
                }
            }

            // Is some random material this material 
            public static bool UsesSameShader(Material m)
            {
                return m.shader.name == Properties.shader.name;
            }

            // Texture, default = "white" { }
            public Texture2D mainTex
            {
                get { return GetTexture (Properties.Instance.mainTexID) as Texture2D; }
                set { SetTexture (Properties.Instance.mainTexID, value); }
            }

            public Vector2 mainTexScale
            {
                get { return GetTextureScale (Properties.mainTexKey); }
                set { SetTextureScale (Properties.mainTexKey, value); }
            }

            public Vector2 mainTexOffset
            {
                get { return GetTextureOffset (Properties.mainTexKey); }
                set { SetTextureOffset (Properties.mainTexKey, value); }
            }

            // Main Color, default = (1,1,1,1)
            public Color color
            {
                get { return GetColor (Properties.Instance.colorID); }
                set { SetColor (Properties.Instance.colorID, value); }
            }

            // Diffuse, default = 2
            public float diff
            {
                get { return GetFloat (Properties.Instance.diffID); }
                set { SetFloat (Properties.Instance.diffID, value); }
            }

            public DiffuseWrap() : base(Properties.shader)
            {
            }

            public DiffuseWrap(string contents) : base(contents)
            {
                base.shader = Properties.shader;
            }

            public DiffuseWrap(Material material) : base(material)
            {
                // Throw exception if this material was not the proper material
                if (material.shader.name != Properties.shader.name)
                    throw new InvalidOperationException("Type Mismatch: Diffuse Wrapped shader required");
            }

        }
    }
}
