// Material wrapper generated by shader translator tool
using System;
using UnityEngine;

namespace Kopernicus
{
    namespace MaterialWrapper
    {
        public class AtmosphereFromGround : Material
        {
            // Internal property ID tracking object
            protected class Properties
            {
                // Return the shader for this wrapper
                private const String shaderName = "AtmosphereFromGround";
                public static Shader shader
                {
                    get { return Shader.Find (shaderName); }
                }

                // Offset Transform, default = (0,0,0,1)
                public const String offsetTransformKey = "_OffsetTransform";
                public Int32 offsetTransformID { get; private set; }

                // Camera Position, default = (0,0,0,0)
                public const String v4CameraPosKey = "_v4CameraPos";
                public Int32 v4CameraPosID { get; private set; }

                // Light Direction, default = (0,0,0,0)
                public const String v4LightDirKey = "_v4LightDir";
                public Int32 v4LightDirID { get; private set; }

                // Inverse WaveLength, default = (0,0,0,0)
                public const String cInvWaveLengthKey = "_cInvWaveLength";
                public Int32 cInvWaveLengthID { get; private set; }

                // Camera Height, default = 0
                public const String fCameraHeightKey = "_fCameraHeight";
                public Int32 fCameraHeightID { get; private set; }

                // Camera Height2, default = 0
                public const String fCameraHeight2Key = "_fCameraHeight2";
                public Int32 fCameraHeight2ID { get; private set; }

                // Outer Radius, default = 0
                public const String fOuterRadiusKey = "_fOuterRadius";
                public Int32 fOuterRadiusID { get; private set; }

                // Outer Radius 2, default = 0
                public const String fOuterRadius2Key = "_fOuterRadius2";
                public Int32 fOuterRadius2ID { get; private set; }

                // Inner Radius, default = 0
                public const String fInnerRadiusKey = "_fInnerRadius";
                public Int32 fInnerRadiusID { get; private set; }

                // Inner Radius 2, default = 0
                public const String fInnerRadius2Key = "_fInnerRadius2";
                public Int32 fInnerRadius2ID { get; private set; }

                // KrESun, default = 0
                public const String fKrESunKey = "_fKrESun";
                public Int32 fKrESunID { get; private set; }

                // KmESun, default = 0
                public const String fKmESunKey = "_fKmESun";
                public Int32 fKmESunID { get; private set; }

                // Kr4PI, default = 0
                public const String fKr4PIKey = "_fKr4PI";
                public Int32 fKr4PIID { get; private set; }

                // Km4PI, default = 0
                public const String fKm4PIKey = "_fKm4PI";
                public Int32 fKm4PIID { get; private set; }

                // Scale, default = 0
                public const String fScaleKey = "_fScale";
                public Int32 fScaleID { get; private set; }

                // Scale Depth, default = 0
                public const String fScaleDepthKey = "_fScaleDepth";
                public Int32 fScaleDepthID { get; private set; }

                // Scale Over Scale Depth, default = 0
                public const String fScaleOverScaleDepthKey = "_fScaleOverScaleDepth";
                public Int32 fScaleOverScaleDepthID { get; private set; }

                // Samples, default = 0
                public const String samplesKey = "_Samples";
                public Int32 samplesID { get; private set; }

                // G, default = 0
                public const String gKey = "_G";
                public Int32 gID { get; private set; }

                // G2, default = 0
                public const String g2Key = "_G2";
                public Int32 g2ID { get; private set; }

                // Exposure, default = 0
                public const String fExposureKey = "_fExposure";
                public Int32 fExposureID { get; private set; }

                // Camera Depth, default = 0
                public const String fCamHeightUnderwaterKey = "_fCamHeightUnderwater";
                public Int32 fCamHeightUnderwaterID { get; private set; }

                // Underwater Opacity Base, default = 0
                public const String underwaterOpacityAltBaseKey = "_underwaterOpacityAltBase";
                public Int32 underwaterOpacityAltBaseID { get; private set; }

                // Underwater Opacity Alt Mult, default = 0
                public const String underwaterOpacityAltMultKey = "_underwaterOpacityAltMult";
                public Int32 underwaterOpacityAltMultID { get; private set; }

                // Underwater Color Start, default = (0,0,0,0)
                public const String underwaterColorStartKey = "_underwaterColorStart";
                public Int32 underwaterColorStartID { get; private set; }

                // Underwater Color End, default = (0,0,0,0)
                public const String underwaterColorEndKey = "_underwaterColorEnd";
                public Int32 underwaterColorEndID { get; private set; }

                // Light dot with upaxis, default = 0
                public const String lightDotKey = "_lightDot";
                public Int32 lightDotID { get; private set; }

                // Singleton instance
                private static Properties singleton = null;
                public static Properties Instance
                {
                    get
                    {
                        // Construct the singleton if it does not exist
                        if(singleton == null)
                            singleton = new Properties();
            
                        return singleton;
                    }
                }

                private Properties()
                {
                    offsetTransformID = Shader.PropertyToID(offsetTransformKey);
                    v4CameraPosID = Shader.PropertyToID(v4CameraPosKey);
                    v4LightDirID = Shader.PropertyToID(v4LightDirKey);
                    cInvWaveLengthID = Shader.PropertyToID(cInvWaveLengthKey);
                    fCameraHeightID = Shader.PropertyToID(fCameraHeightKey);
                    fCameraHeight2ID = Shader.PropertyToID(fCameraHeight2Key);
                    fOuterRadiusID = Shader.PropertyToID(fOuterRadiusKey);
                    fOuterRadius2ID = Shader.PropertyToID(fOuterRadius2Key);
                    fInnerRadiusID = Shader.PropertyToID(fInnerRadiusKey);
                    fInnerRadius2ID = Shader.PropertyToID(fInnerRadius2Key);
                    fKrESunID = Shader.PropertyToID(fKrESunKey);
                    fKmESunID = Shader.PropertyToID(fKmESunKey);
                    fKr4PIID = Shader.PropertyToID(fKr4PIKey);
                    fKm4PIID = Shader.PropertyToID(fKm4PIKey);
                    fScaleID = Shader.PropertyToID(fScaleKey);
                    fScaleDepthID = Shader.PropertyToID(fScaleDepthKey);
                    fScaleOverScaleDepthID = Shader.PropertyToID(fScaleOverScaleDepthKey);
                    samplesID = Shader.PropertyToID(samplesKey);
                    gID = Shader.PropertyToID(gKey);
                    g2ID = Shader.PropertyToID(g2Key);
                    fExposureID = Shader.PropertyToID(fExposureKey);
                    fCamHeightUnderwaterID = Shader.PropertyToID(fCamHeightUnderwaterKey);
                    underwaterOpacityAltBaseID = Shader.PropertyToID(underwaterOpacityAltBaseKey);
                    underwaterOpacityAltMultID = Shader.PropertyToID(underwaterOpacityAltMultKey);
                    underwaterColorStartID = Shader.PropertyToID(underwaterColorStartKey);
                    underwaterColorEndID = Shader.PropertyToID(underwaterColorEndKey);
                    lightDotID = Shader.PropertyToID(lightDotKey);
                }
            }

            // Is some random material this material
            public static Boolean UsesSameShader(Material m)
            {
            	return m.shader.name == Properties.shader.name;
            }

            // Offset Transform, default = (0,0,0,1)
            public Vector4 offsetTransform
            {
                get { return GetVector (Properties.Instance.offsetTransformID); }
                set { SetVector (Properties.Instance.offsetTransformID, value); }
            }

            // Camera Position, default = (0,0,0,0)
            public Vector4 v4CameraPos
            {
                get { return GetVector (Properties.Instance.v4CameraPosID); }
                set { SetVector (Properties.Instance.v4CameraPosID, value); }
            }

            // Light Direction, default = (0,0,0,0)
            public Vector4 v4LightDir
            {
                get { return GetVector (Properties.Instance.v4LightDirID); }
                set { SetVector (Properties.Instance.v4LightDirID, value); }
            }

            // Inverse WaveLength, default = (0,0,0,0)
            public Color cInvWaveLength
            {
                get { return GetColor (Properties.Instance.cInvWaveLengthID); }
                set { SetColor (Properties.Instance.cInvWaveLengthID, value); }
            }

            // Camera Height, default = 0
            public Single fCameraHeight
            {
                get { return GetFloat (Properties.Instance.fCameraHeightID); }
                set { SetFloat (Properties.Instance.fCameraHeightID, value); }
            }

            // Camera Height2, default = 0
            public Single fCameraHeight2
            {
                get { return GetFloat (Properties.Instance.fCameraHeight2ID); }
                set { SetFloat (Properties.Instance.fCameraHeight2ID, value); }
            }

            // Outer Radius, default = 0
            public Single fOuterRadius
            {
                get { return GetFloat (Properties.Instance.fOuterRadiusID); }
                set { SetFloat (Properties.Instance.fOuterRadiusID, value); }
            }

            // Outer Radius 2, default = 0
            public Single fOuterRadius2
            {
                get { return GetFloat (Properties.Instance.fOuterRadius2ID); }
                set { SetFloat (Properties.Instance.fOuterRadius2ID, value); }
            }

            // Inner Radius, default = 0
            public Single fInnerRadius
            {
                get { return GetFloat (Properties.Instance.fInnerRadiusID); }
                set { SetFloat (Properties.Instance.fInnerRadiusID, value); }
            }

            // Inner Radius 2, default = 0
            public Single fInnerRadius2
            {
                get { return GetFloat (Properties.Instance.fInnerRadius2ID); }
                set { SetFloat (Properties.Instance.fInnerRadius2ID, value); }
            }

            // KrESun, default = 0
            public Single fKrESun
            {
                get { return GetFloat (Properties.Instance.fKrESunID); }
                set { SetFloat (Properties.Instance.fKrESunID, value); }
            }

            // KmESun, default = 0
            public Single fKmESun
            {
                get { return GetFloat (Properties.Instance.fKmESunID); }
                set { SetFloat (Properties.Instance.fKmESunID, value); }
            }

            // Kr4PI, default = 0
            public Single fKr4PI
            {
                get { return GetFloat (Properties.Instance.fKr4PIID); }
                set { SetFloat (Properties.Instance.fKr4PIID, value); }
            }

            // Km4PI, default = 0
            public Single fKm4PI
            {
                get { return GetFloat (Properties.Instance.fKm4PIID); }
                set { SetFloat (Properties.Instance.fKm4PIID, value); }
            }

            // Scale, default = 0
            public Single fScale
            {
                get { return GetFloat (Properties.Instance.fScaleID); }
                set { SetFloat (Properties.Instance.fScaleID, value); }
            }

            // Scale Depth, default = 0
            public Single fScaleDepth
            {
                get { return GetFloat (Properties.Instance.fScaleDepthID); }
                set { SetFloat (Properties.Instance.fScaleDepthID, value); }
            }

            // Scale Over Scale Depth, default = 0
            public Single fScaleOverScaleDepth
            {
                get { return GetFloat (Properties.Instance.fScaleOverScaleDepthID); }
                set { SetFloat (Properties.Instance.fScaleOverScaleDepthID, value); }
            }

            // Samples, default = 0
            public Single samples
            {
                get { return GetFloat (Properties.Instance.samplesID); }
                set { SetFloat (Properties.Instance.samplesID, value); }
            }

            // G, default = 0
            public Single g
            {
                get { return GetFloat (Properties.Instance.gID); }
                set { SetFloat (Properties.Instance.gID, value); }
            }

            // G2, default = 0
            public Single g2
            {
                get { return GetFloat (Properties.Instance.g2ID); }
                set { SetFloat (Properties.Instance.g2ID, value); }
            }

            // Exposure, default = 0
            public Single fExposure
            {
                get { return GetFloat (Properties.Instance.fExposureID); }
                set { SetFloat (Properties.Instance.fExposureID, value); }
            }

            // Camera Depth, default = 0
            public Single fCamHeightUnderwater
            {
                get { return GetFloat (Properties.Instance.fCamHeightUnderwaterID); }
                set { SetFloat (Properties.Instance.fCamHeightUnderwaterID, value); }
            }

            // Underwater Opacity Base, default = 0
            public Single underwaterOpacityAltBase
            {
                get { return GetFloat (Properties.Instance.underwaterOpacityAltBaseID); }
                set { SetFloat (Properties.Instance.underwaterOpacityAltBaseID, value); }
            }

            // Underwater Opacity Alt Mult, default = 0
            public Single underwaterOpacityAltMult
            {
                get { return GetFloat (Properties.Instance.underwaterOpacityAltMultID); }
                set { SetFloat (Properties.Instance.underwaterOpacityAltMultID, value); }
            }

            // Underwater Color Start, default = (0,0,0,0)
            public Color underwaterColorStart
            {
                get { return GetColor (Properties.Instance.underwaterColorStartID); }
                set { SetColor (Properties.Instance.underwaterColorStartID, value); }
            }

            // Underwater Color End, default = (0,0,0,0)
            public Color underwaterColorEnd
            {
                get { return GetColor (Properties.Instance.underwaterColorEndID); }
                set { SetColor (Properties.Instance.underwaterColorEndID, value); }
            }

            // Light dot with upaxis, default = 0
            public Single lightDot
            {
                get { return GetFloat (Properties.Instance.lightDotID); }
                set { SetFloat (Properties.Instance.lightDotID, value); }
            }

            public AtmosphereFromGround() : base(Properties.shader)
            {
            }

            [Obsolete("Creating materials from shader source String is no longer supported. Use Shader assets instead.")]
            public AtmosphereFromGround(String contents) : base(contents)
            {
                base.shader = Properties.shader;
            }

            public AtmosphereFromGround(Material material) : base(material)
            {
                // Throw exception if this material was not the proper material
                if (material.shader.name != Properties.shader.name)
                    throw new InvalidOperationException("Type Mismatch: AtmosphereFromGround shader required");
            }

        }
    }
}
