// Material wrapper generated by shader translator tool
using System;
using UnityEngine;

namespace Kopernicus
{
    namespace MaterialWrapper
    {
        public class PQSOceanSurfaceQuadFallback : Material
        {
            // Internal property ID tracking object
            protected class Properties
            {
                // Return the shader for this wrapper
                private const String shaderName = "Terrain/PQS/Ocean Surface Quad (Fallback)";
                public static Shader shader
                {
                    get { return Shader.Find (shaderName); }
                }

                // Main Color, default = (1,1,1,1)
                public const String colorKey = "_Color";
                public Int32 colorID { get; private set; }

                // Color From Space, default = (1,1,1,1)
                public const String colorFromSpaceKey = "_ColorFromSpace";
                public Int32 colorFromSpaceID { get; private set; }

                // Specular Color, default = (1,1,1,1)
                public const String specColorKey = "_SpecColor";
                public Int32 specColorID { get; private set; }

                // Shininess, default = 0.078125
                public const String shininessKey = "_Shininess";
                public Int32 shininessID { get; private set; }

                // Gloss, default = 0.078125
                public const String glossKey = "_Gloss";
                public Int32 glossID { get; private set; }

                // Tex Tiling, default = 1
                public const String tilingKey = "_tiling";
                public Int32 tilingID { get; private set; }

                // Tex0, default = "white" { }
                public const String waterTexKey = "_WaterTex";
                public Int32 waterTexID { get; private set; }

                // Tex1, default = "white" { }
                public const String waterTex1Key = "_WaterTex1";
                public Int32 waterTex1ID { get; private set; }

                // FadeStart, default = 1
                public const String fadeStartKey = "_fadeStart";
                public Int32 fadeStartID { get; private set; }

                // FadeEnd, default = 1
                public const String fadeEndKey = "_fadeEnd";
                public Int32 fadeEndID { get; private set; }

                // PlanetOpacity, default = 1
                public const String planetOpacityKey = "_PlanetOpacity";
                public Int32 planetOpacityID { get; private set; }

                // Singleton instance
                private static Properties singleton = null;
                public static Properties Instance
                {
                    get
                    {
                        // Construct the singleton if it does not exist
                        if(singleton == null)
                            singleton = new Properties();
            
                        return singleton;
                    }
                }

                private Properties()
                {
                    colorID = Shader.PropertyToID(colorKey);
                    colorFromSpaceID = Shader.PropertyToID(colorFromSpaceKey);
                    specColorID = Shader.PropertyToID(specColorKey);
                    shininessID = Shader.PropertyToID(shininessKey);
                    glossID = Shader.PropertyToID(glossKey);
                    tilingID = Shader.PropertyToID(tilingKey);
                    waterTexID = Shader.PropertyToID(waterTexKey);
                    waterTex1ID = Shader.PropertyToID(waterTex1Key);
                    fadeStartID = Shader.PropertyToID(fadeStartKey);
                    fadeEndID = Shader.PropertyToID(fadeEndKey);
                    planetOpacityID = Shader.PropertyToID(planetOpacityKey);
                }
            }

            // Is some random material this material 
            public static Boolean UsesSameShader(Material m)
            {
                return m.shader.name == Properties.shader.name;
            }

            // Main Color, default = (1,1,1,1)
            public new Color color
            {
                get { return GetColor (Properties.Instance.colorID); }
                set { SetColor (Properties.Instance.colorID, value); }
            }

            // Color From Space, default = (1,1,1,1)
            public Color colorFromSpace
            {
                get { return GetColor (Properties.Instance.colorFromSpaceID); }
                set { SetColor (Properties.Instance.colorFromSpaceID, value); }
            }

            // Specular Color, default = (1,1,1,1)
            public Color specColor
            {
                get { return GetColor (Properties.Instance.specColorID); }
                set { SetColor (Properties.Instance.specColorID, value); }
            }

            // Shininess, default = 0.078125
            public Single shininess
            {
                get { return GetFloat (Properties.Instance.shininessID); }
                set { SetFloat (Properties.Instance.shininessID, Mathf.Clamp(value,0.01f,1f)); }
            }

            // Gloss, default = 0.078125
            public Single gloss
            {
                get { return GetFloat (Properties.Instance.glossID); }
                set { SetFloat (Properties.Instance.glossID, Mathf.Clamp(value,0.01f,1f)); }
            }

            // Tex Tiling, default = 1
            public Single tiling
            {
                get { return GetFloat (Properties.Instance.tilingID); }
                set { SetFloat (Properties.Instance.tilingID, value); }
            }

            // Tex0, default = "white" { }
            public Texture2D waterTex
            {
                get { return GetTexture (Properties.Instance.waterTexID) as Texture2D; }
                set { SetTexture (Properties.Instance.waterTexID, value); }
            }

            public Vector2 waterTexScale
            {
                get { return GetTextureScale (Properties.waterTexKey); }
                set { SetTextureScale (Properties.waterTexKey, value); }
            }

            public Vector2 waterTexOffset
            {
                get { return GetTextureOffset (Properties.waterTexKey); }
                set { SetTextureOffset (Properties.waterTexKey, value); }
            }

            // Tex1, default = "white" { }
            public Texture2D waterTex1
            {
                get { return GetTexture (Properties.Instance.waterTex1ID) as Texture2D; }
                set { SetTexture (Properties.Instance.waterTex1ID, value); }
            }

            public Vector2 waterTex1Scale
            {
                get { return GetTextureScale (Properties.waterTex1Key); }
                set { SetTextureScale (Properties.waterTex1Key, value); }
            }

            public Vector2 waterTex1Offset
            {
                get { return GetTextureOffset (Properties.waterTex1Key); }
                set { SetTextureOffset (Properties.waterTex1Key, value); }
            }

            // FadeStart, default = 1
            public Single fadeStart
            {
                get { return GetFloat (Properties.Instance.fadeStartID); }
                set { SetFloat (Properties.Instance.fadeStartID, value); }
            }

            // FadeEnd, default = 1
            public Single fadeEnd
            {
                get { return GetFloat (Properties.Instance.fadeEndID); }
                set { SetFloat (Properties.Instance.fadeEndID, value); }
            }

            // PlanetOpacity, default = 1
            public Single planetOpacity
            {
                get { return GetFloat (Properties.Instance.planetOpacityID); }
                set { SetFloat (Properties.Instance.planetOpacityID, value); }
            }

            public PQSOceanSurfaceQuadFallback() : base(Properties.shader)
            {
            }

            [Obsolete("Creating materials from shader source String is no longer supported. Use Shader assets instead.")]
            public PQSOceanSurfaceQuadFallback(String contents) : base(contents)
            {
                base.shader = Properties.shader;
            }

            public PQSOceanSurfaceQuadFallback(Material material) : base(material)
            {
                // Throw exception if this material was not the proper material
                if (material.shader.name != Properties.shader.name)
                    throw new InvalidOperationException("Type Mismatch: Terrain/PQS/Ocean Surface Quad (Fallback) shader required");
            }

        }
    }
}
