// Material wrapper generated by shader translator tool
using System;
using Kopernicus.MaterialWrapper;
using UnityEngine;

namespace Kopernicus
{
    namespace Configuration
    {
        [RequireConfigType(ConfigType.Node)]
        public class AerialTransCutoutLoader : AerialTransCutout
        {
            // Main Color, default = (1,1,1,1)
            [ParserTarget("color")]
            public ColorParser colorSetter
            {
                get { return color; }
                set { color = value; }
            }

            // Base (RGB) Trans (A), default = "white" { }
            [ParserTarget("mainTex")]
            public Texture2DParser mainTexSetter
            {
                get { return mainTex; }
                set { mainTex = value; }
            }

            [ParserTarget("mainTexScale")]
            private Vector2Parser mainTexScaleSetter
            {
                get { return mainTexScale; }
                set { mainTexScale = value; }
            }

            [ParserTarget("mainTexOffset")]
            private Vector2Parser mainTexOffsetSetter
            {
                get { return mainTexOffset; }
                set { mainTexOffset = value; }
            }

            // Alpha cutoff, default = 0.5
            [ParserTarget("texCutoff")]
            public NumericParser<Single> texCutoffSetter
            {
                get { return texCutoff; }
                set { texCutoff = value; }
            }

            // AP Fog Color, default = (0,0,1,1)
            [ParserTarget("fogColor")]
            public ColorParser fogColorSetter
            {
                get { return fogColor; }
                set { fogColor = value; }
            }

            // AP Height Fall Off, default = 1
            [ParserTarget("heightFallOff")]
            public NumericParser<Single> heightFallOffSetter
            {
                get { return heightFallOff; }
                set { heightFallOff = value; }
            }

            // AP Global Density, default = 1
            [ParserTarget("globalDensity")]
            public NumericParser<Single> globalDensitySetter
            {
                get { return globalDensity; }
                set { globalDensity = value; }
            }

            // AP Atmosphere Depth, default = 1
            [ParserTarget("atmosphereDepth")]
            public NumericParser<Single> atmosphereDepthSetter
            {
                get { return atmosphereDepth; }
                set { atmosphereDepth = value; }
            }

            // Constructors
            public AerialTransCutoutLoader () : base() { }
            [Obsolete("Creating materials from shader source String is no longer supported. Use Shader assets instead.")]
            public AerialTransCutoutLoader (String contents) : base (contents) { }
            public AerialTransCutoutLoader (Material material) : base(material) { }
        }
    }
}
