// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class PQSMainShaderLoader : PQSMainShader
        {
            // Saturation, default = 1
            [ParserTarget("saturation")]
            public NumericParser<float> saturationSetter
            {
                get { return saturation; }
                set { saturation = value; }
            }

            // Contrast, default = 1
            [ParserTarget("contrast")]
            public NumericParser<float> contrastSetter
            {
                get { return contrast; }
                set { contrast = value; }
            }

            // Colour Unsaturation (A = Factor), default = (1,1,1,0)
            [ParserTarget("tintColor")]
            public ColorParser tintColorSetter
            {
                get { return tintColor; }
                set { tintColor = value; }
            }

            // Near Blend, default = 0.5
            [ParserTarget("powerNear")]
            public NumericParser<float> powerNearSetter
            {
                get { return powerNear; }
                set { powerNear = value; }
            }

            // Far Blend, default = 0.5
            [ParserTarget("powerFar")]
            public NumericParser<float> powerFarSetter
            {
                get { return powerFar; }
                set { powerFar = value; }
            }

            // NearFar Start, default = 2000
            [ParserTarget("groundTexStart")]
            public NumericParser<float> groundTexStartSetter
            {
                get { return groundTexStart; }
                set { groundTexStart = value; }
            }

            // NearFar End, default = 10000
            [ParserTarget("groundTexEnd")]
            public NumericParser<float> groundTexEndSetter
            {
                get { return groundTexEnd; }
                set { groundTexEnd = value; }
            }

            // Steep Blend, default = 1
            [ParserTarget("steepPower")]
            public NumericParser<float> steepPowerSetter
            {
                get { return steepPower; }
                set { steepPower = value; }
            }

            // Steep Fade Start, default = 20000
            [ParserTarget("steepTexStart")]
            public NumericParser<float> steepTexStartSetter
            {
                get { return steepTexStart; }
                set { steepTexStart = value; }
            }

            // Steep Fade End, default = 30000
            [ParserTarget("steepTexEnd")]
            public NumericParser<float> steepTexEndSetter
            {
                get { return steepTexEnd; }
                set { steepTexEnd = value; }
            }

            // Steep Texture, default = "white" { }
            [ParserTarget("steepTex")]
            public Texture2DParser steepTexSetter
            {
                get { return steepTex; }
                set { steepTex = value; }
            }

            [ParserTarget("steepTexScale")]
            private Vector2Parser steepTexScaleSetter
            {
                get { return steepTexScale; }
                set { steepTexScale = value; }
            }

            [ParserTarget("steepTexOffset")]
            private Vector2Parser steepTexOffsetSetter
            {
                get { return steepTexOffset; }
                set { steepTexOffset = value; }
            }

            // Steep Bump Map, default = "bump" { }
            [ParserTarget("steepBumpMap")]
            public Texture2DParser steepBumpMapSetter
            {
                get { return steepBumpMap; }
                set { steepBumpMap = value; }
            }

            [ParserTarget("steepBumpMapScale")]
            private Vector2Parser steepBumpMapScaleSetter
            {
                get { return steepBumpMapScale; }
                set { steepBumpMapScale = value; }
            }

            [ParserTarget("steepBumpMapOffset")]
            private Vector2Parser steepBumpMapOffsetSetter
            {
                get { return steepBumpMapOffset; }
                set { steepBumpMapOffset = value; }
            }

            // Steep Near Tiling, default = 1
            [ParserTarget("steepNearTiling")]
            public NumericParser<float> steepNearTilingSetter
            {
                get { return steepNearTiling; }
                set { steepNearTiling = value; }
            }

            // Steep Far Tiling, default = 1
            [ParserTarget("steepTiling")]
            public NumericParser<float> steepTilingSetter
            {
                get { return steepTiling; }
                set { steepTiling = value; }
            }

            // Low Texture, default = "white" { }
            [ParserTarget("lowTex")]
            public Texture2DParser lowTexSetter
            {
                get { return lowTex; }
                set { lowTex = value; }
            }

            [ParserTarget("lowTexScale")]
            private Vector2Parser lowTexScaleSetter
            {
                get { return lowTexScale; }
                set { lowTexScale = value; }
            }

            [ParserTarget("lowTexOffset")]
            private Vector2Parser lowTexOffsetSetter
            {
                get { return lowTexOffset; }
                set { lowTexOffset = value; }
            }

            // Low Bump Map, default = "bump" { }
            [ParserTarget("lowBumpMap")]
            public Texture2DParser lowBumpMapSetter
            {
                get { return lowBumpMap; }
                set { lowBumpMap = value; }
            }

            [ParserTarget("lowBumpMapScale")]
            private Vector2Parser lowBumpMapScaleSetter
            {
                get { return lowBumpMapScale; }
                set { lowBumpMapScale = value; }
            }

            [ParserTarget("lowBumpMapOffset")]
            private Vector2Parser lowBumpMapOffsetSetter
            {
                get { return lowBumpMapOffset; }
                set { lowBumpMapOffset = value; }
            }

            // Low Near Tiling, default = 1000
            [ParserTarget("lowNearTiling")]
            public NumericParser<float> lowNearTilingSetter
            {
                get { return lowNearTiling; }
                set { lowNearTiling = value; }
            }

            // Low Far Tiling, default = 10
            [ParserTarget("lowMultiFactor")]
            public NumericParser<float> lowMultiFactorSetter
            {
                get { return lowMultiFactor; }
                set { lowMultiFactor = value; }
            }

            // Low Bump Near Tiling, default = 1
            [ParserTarget("lowBumpNearTiling")]
            public NumericParser<float> lowBumpNearTilingSetter
            {
                get { return lowBumpNearTiling; }
                set { lowBumpNearTiling = value; }
            }

            // Low Bump Far Tiling, default = 1
            [ParserTarget("lowBumpFarTiling")]
            public NumericParser<float> lowBumpFarTilingSetter
            {
                get { return lowBumpFarTiling; }
                set { lowBumpFarTiling = value; }
            }

            // Mid Texture, default = "white" { }
            [ParserTarget("midTex")]
            public Texture2DParser midTexSetter
            {
                get { return midTex; }
                set { midTex = value; }
            }

            [ParserTarget("midTexScale")]
            private Vector2Parser midTexScaleSetter
            {
                get { return midTexScale; }
                set { midTexScale = value; }
            }

            [ParserTarget("midTexOffset")]
            private Vector2Parser midTexOffsetSetter
            {
                get { return midTexOffset; }
                set { midTexOffset = value; }
            }

            // Mid Bump Map, default = "bump" { }
            [ParserTarget("midBumpMap")]
            public Texture2DParser midBumpMapSetter
            {
                get { return midBumpMap; }
                set { midBumpMap = value; }
            }

            [ParserTarget("midBumpMapScale")]
            private Vector2Parser midBumpMapScaleSetter
            {
                get { return midBumpMapScale; }
                set { midBumpMapScale = value; }
            }

            [ParserTarget("midBumpMapOffset")]
            private Vector2Parser midBumpMapOffsetSetter
            {
                get { return midBumpMapOffset; }
                set { midBumpMapOffset = value; }
            }

            // Mid Near Tiling, default = 1000
            [ParserTarget("midNearTiling")]
            public NumericParser<float> midNearTilingSetter
            {
                get { return midNearTiling; }
                set { midNearTiling = value; }
            }

            // Mid Far Tiling, default = 10
            [ParserTarget("midMultiFactor")]
            public NumericParser<float> midMultiFactorSetter
            {
                get { return midMultiFactor; }
                set { midMultiFactor = value; }
            }

            // Mid Bump Near Tiling, default = 1
            [ParserTarget("midBumpNearTiling")]
            public NumericParser<float> midBumpNearTilingSetter
            {
                get { return midBumpNearTiling; }
                set { midBumpNearTiling = value; }
            }

            // Mid Bump Far Tiling, default = 1
            [ParserTarget("midBumpFarTiling")]
            public NumericParser<float> midBumpFarTilingSetter
            {
                get { return midBumpFarTiling; }
                set { midBumpFarTiling = value; }
            }

            // High Texture, default = "white" { }
            [ParserTarget("highTex")]
            public Texture2DParser highTexSetter
            {
                get { return highTex; }
                set { highTex = value; }
            }

            [ParserTarget("highTexScale")]
            private Vector2Parser highTexScaleSetter
            {
                get { return highTexScale; }
                set { highTexScale = value; }
            }

            [ParserTarget("highTexOffset")]
            private Vector2Parser highTexOffsetSetter
            {
                get { return highTexOffset; }
                set { highTexOffset = value; }
            }

            // High Bump Map, default = "bump" { }
            [ParserTarget("highBumpMap")]
            public Texture2DParser highBumpMapSetter
            {
                get { return highBumpMap; }
                set { highBumpMap = value; }
            }

            [ParserTarget("highBumpMapScale")]
            private Vector2Parser highBumpMapScaleSetter
            {
                get { return highBumpMapScale; }
                set { highBumpMapScale = value; }
            }

            [ParserTarget("highBumpMapOffset")]
            private Vector2Parser highBumpMapOffsetSetter
            {
                get { return highBumpMapOffset; }
                set { highBumpMapOffset = value; }
            }

            // High Near Tiling, default = 1000
            [ParserTarget("highNearTiling")]
            public NumericParser<float> highNearTilingSetter
            {
                get { return highNearTiling; }
                set { highNearTiling = value; }
            }

            // High Far Tiling, default = 10
            [ParserTarget("highMultiFactor")]
            public NumericParser<float> highMultiFactorSetter
            {
                get { return highMultiFactor; }
                set { highMultiFactor = value; }
            }

            // High Bump Near Tiling, default = 1
            [ParserTarget("highBumpNearTiling")]
            public NumericParser<float> highBumpNearTilingSetter
            {
                get { return highBumpNearTiling; }
                set { highBumpNearTiling = value; }
            }

            // High Bump Far Tiling, default = 1
            [ParserTarget("highBumpFarTiling")]
            public NumericParser<float> highBumpFarTilingSetter
            {
                get { return highBumpFarTiling; }
                set { highBumpFarTiling = value; }
            }

            // Low Transition Start, default = 0
            [ParserTarget("lowStart")]
            public NumericParser<float> lowStartSetter
            {
                get { return lowStart; }
                set { lowStart = value; }
            }

            // Low Transition End, default = 0.3
            [ParserTarget("lowEnd")]
            public NumericParser<float> lowEndSetter
            {
                get { return lowEnd; }
                set { lowEnd = value; }
            }

            // High Transition Start, default = 0.8
            [ParserTarget("highStart")]
            public NumericParser<float> highStartSetter
            {
                get { return highStart; }
                set { highStart = value; }
            }

            // High Transition End, default = 1
            [ParserTarget("highEnd")]
            public NumericParser<float> highEndSetter
            {
                get { return highEnd; }
                set { highEnd = value; }
            }

            // AP Global Density, default = 1
            [ParserTarget("globalDensity")]
            public NumericParser<float> globalDensitySetter
            {
                get { return globalDensity; }
                set { globalDensity = value; }
            }

            // FogColorRamp, default = "white" { }
            [ParserTarget("fogColorRamp")]
            public Texture2DParser fogColorRampSetter
            {
                get { return fogColorRamp; }
                set { fogColorRamp = value; }
            }

            [ParserTarget("fogColorRampScale")]
            private Vector2Parser fogColorRampScaleSetter
            {
                get { return fogColorRampScale; }
                set { fogColorRampScale = value; }
            }

            [ParserTarget("fogColorRampOffset")]
            private Vector2Parser fogColorRampOffsetSetter
            {
                get { return fogColorRampOffset; }
                set { fogColorRampOffset = value; }
            }

            // PlanetOpacity, default = 1
            [ParserTarget("planetOpacity")]
            public NumericParser<float> planetOpacitySetter
            {
                get { return planetOpacity; }
                set { planetOpacity = value; }
            }

            // Constructors
            public PQSMainShaderLoader () : base() { }
            public PQSMainShaderLoader (string contents) : base (contents) { }
            public PQSMainShaderLoader (Material material) : base(material) { }
        }
    }
}
