// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class ScaledPlanetSimpleLoader : ScaledPlanetSimple
        {
            // Main Color, default = (1,1,1,1)
            [ParserTarget("color", optional = true)]
            public ColorParser colorSetter
            {
                get { return color; }
                set { color = value; }
            }

            // Specular Color, default = (0.5,0.5,0.5,1)
            [ParserTarget("specColor", optional = true)]
            public ColorParser specColorSetter
            {
                get { return specColor; }
                set { specColor = value; }
            }

            // Shininess, default = 0.078125
            [ParserTarget("shininess", optional = true)]
            public NumericParser<float> shininessSetter
            {
                get { return shininess; }
                set { shininess = value; }
            }

            [ParserTarget("texture", optional = true)]
            public Texture2DParser textureSetter
            {
                get { return mainTex; }
                set { mainTex = value; }
            }

            // Base (RGB) Gloss (A), default = "white" { }
            [ParserTarget("mainTex", optional = true)]
            public Texture2DParser mainTexSetter
            {
                get { return mainTex; }
                set { mainTex = value; }
            }

            [ParserTarget("mainTexScale", optional = true)]
            private Vector2Parser mainTexScaleSetter
            {
                get { return mainTexScale; }
                set { mainTexScale = value; }
            }

            [ParserTarget("mainTexOffset", optional = true)]
            private Vector2Parser mainTexOffsetSetter
            {
                get { return mainTexOffset; }
                set { mainTexOffset = value; }
            }

            [ParserTarget("normals", optional = true)]
            public Texture2DParser normalsSetter
            {
                get { return bumpMap; }
                set { bumpMap = value; }
            }

            // Normalmap, default = "bump" { }
            [ParserTarget("bumpMap", optional = true)]
            public Texture2DParser bumpMapSetter
            {
                get { return bumpMap; }
                set { bumpMap = value; }
            }

            [ParserTarget("bumpMapScale", optional = true)]
            private Vector2Parser bumpMapScaleSetter
            {
                get { return bumpMapScale; }
                set { bumpMapScale = value; }
            }

            [ParserTarget("bumpMapOffset", optional = true)]
            private Vector2Parser bumpMapOffsetSetter
            {
                get { return bumpMapOffset; }
                set { bumpMapOffset = value; }
            }

            // Opacity, default = 1
            [ParserTarget("opacity", optional = true)]
            public NumericParser<float> opacitySetter
            {
                get { return opacity; }
                set { opacity = value; }
            }

            // Resource Map (RGB), default = "black" { }
            [ParserTarget("resourceMap", optional = true)]
            public Texture2DParser resourceMapSetter
            {
                get { return resourceMap; }
                set { resourceMap = value; }
            }

            [ParserTarget("resourceMapScale", optional = true)]
            private Vector2Parser resourceMapScaleSetter
            {
                get { return resourceMapScale; }
                set { resourceMapScale = value; }
            }

            [ParserTarget("resourceMapOffset", optional = true)]
            private Vector2Parser resourceMapOffsetSetter
            {
                get { return resourceMapOffset; }
                set { resourceMapOffset = value; }
            }

            // Constructors
            public ScaledPlanetSimpleLoader () : base() { }
            public ScaledPlanetSimpleLoader (string contents) : base (contents) { }
            public ScaledPlanetSimpleLoader (Material material) : base(material) { }
        }
    }
}
