// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class AlphaTestDiffuseLoader : AlphaTestDiffuse
        {
            // Main Color, default = (1,1,1,1)
            [ParserTarget("color", optional = true)]
            public ColorParser colorSetter
            {
                get { return color; }
                set { color = value; }
            }

            // Base (RGB) Trans (A), default = "white" {}
            [ParserTarget("mainTex", optional = true)]
            public Texture2DParser mainTexSetter
            {
                get { return mainTex; }
                set { mainTex = value; }
            }

            [ParserTarget("mainTexScale", optional = true)]
            public Vector2Parser mainTexScaleSetter
            {
                get { return mainTexScale; }
                set { mainTexScale = value; }
            }

            [ParserTarget("mainTexOffset", optional = true)]
            public Vector2Parser mainTexOffsetSetter
            {
                get { return mainTexOffset; }
                set { mainTexOffset = value; }
            }

            // Alpha cutoff, default = 0.5
            [ParserTarget("cutoff", optional = true)]
            public NumericParser<float> cutoffSetter
            {
                get { return cutoff; }
                set { cutoff = value; }
            }

            // Constructors
            public AlphaTestDiffuseLoader () : base() { }
            public AlphaTestDiffuseLoader (string contents) : base (contents) { }
            public AlphaTestDiffuseLoader (Material material) : base(material) { }
        }
    }
}
