// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class DiffuseWrapLoader : DiffuseWrap
        {
            // Texture, default = "white" {}
            [ParserTarget("mainTex", optional = true)]
            private Texture2DParser mainTexSetter
            {
                set { base.mainTex = value.value; }
            }

            [ParserTarget("mainTexScale", optional = true)]
            private Vector2Parser mainTexScaleSetter
            {
                set { base.mainTexScale = value.value; }
            }

            [ParserTarget("mainTexOffset", optional = true)]
            private Vector2Parser mainTexOffsetSetter
            {
                set { base.mainTexOffset = value.value; }
            }

            // Main Color, default = (1,1,1,1)
            [ParserTarget("color", optional = true)]
            private ColorParser colorSetter
            {
                set { base.color = value.value; }
            }

            // Diffuse, default = 2
            [ParserTarget("diff", optional = true)]
            private NumericParser<float> diffSetter
            {
                set { base.diff = value.value; }
            }

            // Constructors
            public DiffuseWrapLoader () : base() { }
            public DiffuseWrapLoader (string contents) : base (contents) { }
            public DiffuseWrapLoader (Material material) : base(material) { }
        }
    }
}
