// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class NormalDiffuseDetailLoader : NormalDiffuseDetail
        {
            // Main Color, default = (1,1,1,1)
            [ParserTarget("color", optional = true)]
            public ColorParser colorSetter
            {
                get { return color; }
                set { color = value; }
            }

            // Base (RGB), default = "white" {}
            [ParserTarget("mainTex", optional = true)]
            public Texture2DParser mainTexSetter
            {
                get { return mainTex; }
                set { mainTex = value; }
            }

            [ParserTarget("mainTexScale", optional = true)]
            public Vector2Parser mainTexScaleSetter
            {
                get { return mainTexScale; }
                set { mainTexScale = value; }
            }

            [ParserTarget("mainTexOffset", optional = true)]
            public Vector2Parser mainTexOffsetSetter
            {
                get { return mainTexOffset; }
                set { mainTexOffset = value; }
            }

            // Detail (RGB), default = "gray" {}
            [ParserTarget("detail", optional = true)]
            public Texture2DParser detailSetter
            {
                get { return detail; }
                set { detail = value; }
            }

            [ParserTarget("detailScale", optional = true)]
            public Vector2Parser detailScaleSetter
            {
                get { return detailScale; }
                set { detailScale = value; }
            }

            [ParserTarget("detailOffset", optional = true)]
            public Vector2Parser detailOffsetSetter
            {
                get { return detailOffset; }
                set { detailOffset = value; }
            }

            // Constructors
            public NormalDiffuseDetailLoader () : base() { }
            public NormalDiffuseDetailLoader (string contents) : base (contents) { }
            public NormalDiffuseDetailLoader (Material material) : base(material) { }
        }
    }
}
