// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

using Kopernicus.MaterialWrapper;

namespace Kopernicus
{
    namespace Configuration
    {
        public class NormalDiffuseDetailLoader : NormalDiffuseDetail
        {
            // Main Color, default = (1,1,1,1)
            [ParserTarget("color", optional = true)]
            private ColorParser colorSetter
            {
                set { base.color = value.value; }
            }

            // Base (RGB), default = "white" {}
            [ParserTarget("mainTex", optional = true)]
            private Texture2DParser mainTexSetter
            {
                set { base.mainTex = value.value; }
            }

            [ParserTarget("mainTexScale", optional = true)]
            private Vector2Parser mainTexScaleSetter
            {
                set { base.mainTexScale = value.value; }
            }

            [ParserTarget("mainTexOffset", optional = true)]
            private Vector2Parser mainTexOffsetSetter
            {
                set { base.mainTexOffset = value.value; }
            }

            // Detail (RGB), default = "gray" {}
            [ParserTarget("detail", optional = true)]
            private Texture2DParser detailSetter
            {
                set { base.detail = value.value; }
            }

            [ParserTarget("detailScale", optional = true)]
            private Vector2Parser detailScaleSetter
            {
                set { base.detailScale = value.value; }
            }

            [ParserTarget("detailOffset", optional = true)]
            private Vector2Parser detailOffsetSetter
            {
                set { base.detailOffset = value.value; }
            }

            // Constructors
            public NormalDiffuseDetailLoader () : base() { }
            public NormalDiffuseDetailLoader (string contents) : base (contents) { }
            public NormalDiffuseDetailLoader (Material material) : base(material) { }
        }
    }
}
