// Material wrapper generated by shader translator tool
using System;
using System.Reflection;
using UnityEngine;

namespace Kopernicus
{
    namespace MaterialWrapper
    {
        public class PQSOceanSurfaceQuad : Material
        {
            // Return the shader for this wrapper
            private const string shaderName = "Terrain/PQS/Ocean Surface Quad";
            private static Shader shaderForMaterial
            {
                get { return Shader.Find (shaderName); }
            }

            // Color From Space, default = (1,1,1,1)
            private const string colorFromSpaceKey = "_ColorFromSpace";
            public Color colorFromSpace
            {
                get { return GetColor (colorFromSpaceKey); }
                set { SetColor (colorFromSpaceKey, value); }
            }

            // Specular Color, default = (1,1,1,1)
            private const string specColorKey = "_SpecColor";
            public Color specColor
            {
                get { return GetColor (specColorKey); }
                set { SetColor (specColorKey, value); }
            }

            // Shininess, default = 0.078125
            private const string shininessKey = "_Shininess";
            public float shininess
            {
                get { return GetFloat (shininessKey); }
                set { SetFloat (shininessKey, Mathf.Clamp(value,0.01f,1f)); }
            }

            // Gloss, default = 0.078125
            private const string glossKey = "_Gloss";
            public float gloss
            {
                get { return GetFloat (glossKey); }
                set { SetFloat (glossKey, Mathf.Clamp(value,0.01f,1f)); }
            }

            // Tex Tiling, default = 1
            private const string tilingKey = "_tiling";
            public float tiling
            {
                get { return GetFloat (tilingKey); }
                set { SetFloat (tilingKey, value); }
            }

            // Tex0, default = "white" {}
            private const string waterTexKey = "_WaterTex";
            public Texture2D waterTex
            {
                get { return GetTexture (waterTexKey) as Texture2D; }
                set { SetTexture (waterTexKey, value); }
            }

            // Tex1, default = "white" {}
            private const string waterTex1Key = "_WaterTex1";
            public Texture2D waterTex1
            {
                get { return GetTexture (waterTex1Key) as Texture2D; }
                set { SetTexture (waterTex1Key, value); }
            }

            // Normal Tiling, default = 1
            private const string bTilingKey = "_bTiling";
            public float bTiling
            {
                get { return GetFloat (bTilingKey); }
                set { SetFloat (bTilingKey, value); }
            }

            // Normalmap0, default = "bump" {}
            private const string bumpMapKey = "_BumpMap";
            public Texture2D bumpMap
            {
                get { return GetTexture (bumpMapKey) as Texture2D; }
                set { SetTexture (bumpMapKey, value); }
            }

            // Water Movement, default = 1
            private const string displacementKey = "_displacement";
            public float displacement
            {
                get { return GetFloat (displacementKey); }
                set { SetFloat (displacementKey, value); }
            }

            // Water Freq, default = 1
            private const string dispFreqKey = "_dispFreq";
            public float dispFreq
            {
                get { return GetFloat (dispFreqKey); }
                set { SetFloat (dispFreqKey, value); }
            }

            // Mix, default = 1
            private const string mixKey = "_Mix";
            public float mix
            {
                get { return GetFloat (mixKey); }
                set { SetFloat (mixKey, value); }
            }

            // Opacity, default = 1
            private const string oceanOpacityKey = "_oceanOpacity";
            public float oceanOpacity
            {
                get { return GetFloat (oceanOpacityKey); }
                set { SetFloat (oceanOpacityKey, value); }
            }

            // Falloff Power, default = 1
            private const string falloffPowerKey = "_falloffPower";
            public float falloffPower
            {
                get { return GetFloat (falloffPowerKey); }
                set { SetFloat (falloffPowerKey, value); }
            }

            // Falloff Exp, default = 2
            private const string falloffExpKey = "_falloffExp";
            public float falloffExp
            {
                get { return GetFloat (falloffExpKey); }
                set { SetFloat (falloffExpKey, value); }
            }

            // AP Fog Color, default = (0,0,1,1)
            private const string fogColorKey = "_fogColor";
            public Color fogColor
            {
                get { return GetColor (fogColorKey); }
                set { SetColor (fogColorKey, value); }
            }

            // AP Height Fall Off, default = 1
            private const string heightFallOffKey = "_heightFallOff";
            public float heightFallOff
            {
                get { return GetFloat (heightFallOffKey); }
                set { SetFloat (heightFallOffKey, value); }
            }

            // AP Global Density, default = 1
            private const string globalDensityKey = "_globalDensity";
            public float globalDensity
            {
                get { return GetFloat (globalDensityKey); }
                set { SetFloat (globalDensityKey, value); }
            }

            // AP Atmosphere Depth, default = 1
            private const string atmosphereDepthKey = "_atmosphereDepth";
            public float atmosphereDepth
            {
                get { return GetFloat (atmosphereDepthKey); }
                set { SetFloat (atmosphereDepthKey, value); }
            }

            // FogColorRamp, default = "white" {}
            private const string fogColorRampKey = "_fogColorRamp";
            public Texture2D fogColorRamp
            {
                get { return GetTexture (fogColorRampKey) as Texture2D; }
                set { SetTexture (fogColorRampKey, value); }
            }

            // FadeStart, default = 1
            private const string fadeStartKey = "_fadeStart";
            public float fadeStart
            {
                get { return GetFloat (fadeStartKey); }
                set { SetFloat (fadeStartKey, value); }
            }

            // FadeEnd, default = 1
            private const string fadeEndKey = "_fadeEnd";
            public float fadeEnd
            {
                get { return GetFloat (fadeEndKey); }
                set { SetFloat (fadeEndKey, value); }
            }

            // PlanetOpacity, default = 1
            private const string planetOpacityKey = "_PlanetOpacity";
            public float planetOpacity
            {
                get { return GetFloat (planetOpacityKey); }
                set { SetFloat (planetOpacityKey, value); }
            }

            public PQSOceanSurfaceQuad() : base(shaderForMaterial)
            {
            }

            public PQSOceanSurfaceQuad(string contents) : base(contents)
            {
                base.shader = shaderForMaterial;
            }

            public PQSOceanSurfaceQuad(Material material) : base(material)
            {
                // Throw exception if this material was not the proper material
                if (material.shader.name != shaderName)
                    throw new InvalidOperationException("PQSOceanSurfaceQuad material requires the \"" + shaderName + "\" shader");
            }

        }
    }
}
